Repository MeAlam1/BlueLib, pull requests merged in 2025-01, with the labels that each got.

#97 Add interfaces for tamable, flying, and swimming entities (Issue #63)
  common/src/main/java/software/bluelib/entity/EntityStateManager.java
  common/src/main/java/software/bluelib/interfaces/entity/IFlyingEntity.java
  common/src/main/java/software/bluelib/interfaces/entity/ISwimmingEntity.java
  common/src/main/java/software/bluelib/interfaces/entity/ITamableEntity.java
  common/src/main/java/software/bluelib/interfaces/platform/IPlatformHelper.java
  common/src/main/java/software/bluelib/interfaces/variant/IVariantEntity.java
  common/src/main/java/software/bluelib/interfaces/variant/base/IVariantEntityBase.java
  common/src/main/java/software/bluelib/markdown/MarkdownParser.java
  common/src/main/java/software/bluelib/markdown/syntax/Bold.java
  common/src/main/java/software/bluelib/markdown/syntax/Color.java
  common/src/main/java/software/bluelib/markdown/syntax/CopyToClipboard.java
  common/src/main/java/software/bluelib/markdown/syntax/Hyperlink.java
  common/src/main/java/software/bluelib/markdown/syntax/Italic.java
  common/src/main/java/software/bluelib/markdown/syntax/Spoiler.java
  common/src/main/java/software/bluelib/markdown/syntax/Strikethrough.java
  common/src/main/java/software/bluelib/markdown/syntax/Underline.java
  common/src/main/java/software/bluelib/utils/IsValidUtils.java
  common/src/main/java/software/bluelib/utils/conversion/CaseConverterUtils.java
  common/src/main/java/software/bluelib/utils/conversion/ColorConversionUtils.java
  common/src/main/java/software/bluelib/utils/conversion/MathConverterUtils.java
  common/src/main/java/software/bluelib/utils/logging/BaseLogLevel.java
  common/src/main/java/software/bluelib/utils/logging/BaseLogger.java
  common/src/main/java/software/bluelib/utils/logging/DefaultLogColorProvider.java
  common/src/main/java/software/bluelib/utils/logging/LoggerConfig.java
  common/src/main/java/software/bluelib/utils/math/AlgebraicUtils.java
  common/src/main/java/software/bluelib/utils/math/GeometricUtils.java
  common/src/main/java/software/bluelib/utils/math/MatrixUtils.java
  common/src/main/java/software/bluelib/utils/math/RandomGenUtils.java
  common/src/main/java/software/bluelib/utils/math/StatisticalUtils.java
  common/src/main/java/software/bluelib/utils/minecraft/ChunkUtils.java
  common/src/main/java/software/bluelib/utils/variant/ParameterUtils.java
Labels: Enhancement, 1.21, NeoForge, Fabric

#100 Fixed /reload on Fabric
  fabric/src/main/java/software/bluelib/BlueLib.java
  fabric/src/main/java/software/bluelib/example/event/ReloadHandler.java
Labels: Bug, 1.21, Fabric

#102 Added the Final things of 1.7.0
  .github/workflows/code_quality.yml
  .gitignore
  common/src/main/java/software/bluelib/BlueLibConstants.java
  common/src/main/java/software/bluelib/entity/EntityStateManager.java
  common/src/main/java/software/bluelib/interfaces/entity/IFlyingEntity.java
  common/src/main/java/software/bluelib/interfaces/entity/ISwimmingEntity.java
  common/src/main/java/software/bluelib/interfaces/entity/ITamableEntity.java
  common/src/main/java/software/bluelib/markdown/syntax/Color.java
  common/src/main/java/software/bluelib/test/markdown/syntax/SpoilerTest.java
  common/src/main/java/software/bluelib/utils/math/RandomGenUtils.java
  gradle.properties
  qodana.yaml
Labels: Enhancement, 1.21, NeoForge, Fabric, Cleanup
